### ISSUE TITLE
spring-react-issue

### ISSUE THREAD

**Issue by BillySadge** [kkkrupenich/pract#16]
https://github.com/kkkrupenich/pract/blob/47a49c7753c5bdb473d7199c194a1cff755dc40c/spring/src/main/java/com/example/spring/controllers/CardController.java#L21
лучше всё же добавить private final 

https://github.com/kkkrupenich/pract/blob/47a49c7753c5bdb473d7199c194a1cff755dc40c/spring/src/main/java/com/example/spring/services/CardService.java#L30-L41

на первое сонар должен был ругаться, можно с помощью Optional в ином случае выкинуть какой-нибудь exception например
```
public Card getCardById(Long id) {
    return cardRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("Card with ID " + id + " not found"));
}
```
в втором случае идея (если ты в идее пишешь конечно) предлагает заменить на 
 ```
public Card getCardByNumber(Long number) {
    Optional<Card> card = cardRepository.findByNumber(number);
    return card.orElse(null);
}
```
https://github.com/kkkrupenich/pract/blob/47a49c7753c5bdb473d7199c194a1cff755dc40c/spring/src/main/java/com/example/spring/services/UserService.java#L64-L66 тут я так понимаю просто лишняя строка

 

https://github.com/kkkrupenich/pract/blob/47a49c7753c5bdb473d7199c194a1cff755dc40c/reactfront/src/services/cardService.js#L3-L28 

не очень понятно сразу использовать один endpoint на `add` и `update` , наверное было бы понятнее сделать ещё один endpoint (`Put` или `Patch`) на бэке   

https://github.com/kkkrupenich/pract/blob/47a49c7753c5bdb473d7199c194a1cff755dc40c/reactfront/src/routes/updateCard.js#L42-L45
`await` пропустил

**Comment by kkkrupenich** [comment]
1) Исправлю
2) Действительно сонар ругается, поэтому я это исправлял проверкой isEmpty, в таком случае выкидывал NotFoundException, иначе возвращал сущность (оно уже исправлено, просто не закоммитил)
3) И правда лишняя
4) Я хотел разделить add и update на два метода в бэке, но в определенный момент мне стало лень если честно) Исправлю
5) Исправлю

**Comment by kkkrupenich** [comment]
Исправил
